export class AppStrings {
  static readonly APP_NAME: string = '做个决定';
  static readonly WHEEL: string = '幸运转盘';
  static readonly DRAW: string = '抽签';
  static readonly FINGER_SELECT: string = '指尖选择';
  static readonly COIN: string = '抛硬币';
  static readonly YES_NO: string = '是或否';
  static readonly RANDOM_NUMBER: string = '随机数字';
  static readonly HISTORY: string = '历史记录';
  static readonly SETTINGS: string = '设置';
  static readonly PRIVACY: string = '隐私说明';
  static readonly SAVE_FAILED: string = '保存失败，请重试';
  static readonly SAVED: string = '已保存';
}
